export const REQ_POSTS_DATA = "FETCH_POSTS_DATA";
export const RESOLVE_POSTS_DATA = "RESOLVE_POSTS_DATA";
export const ERROR_POSTS_DATA = "ERROR_POSTS_DATA";


export const REQ_POST_DATA = "FETCH_POST_DATA"
export const RESOLVE_POST_DATA = "RESOLVE_POST_DATA"
export const ERROR_POST_DATA = "ERROR_POST_DATA"
